services:
  - type: web
    name: blogify-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn blogify.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: blogify-db
          property: connectionString